// Builds the exercises seed migration from docs/exercise-library.json.
//
// Usage:
//   node scripts/build-seed.mjs > supabase/migrations/<timestamp>_seed_exercises.sql
//
// The output upserts every exercise, so if the library changes, running this
// again into a new migration updates the rows in place. It stops with an error
// if the library has a mistake the database would reject or the engine would
// trip over.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const libraryPath = fileURLToPath(new URL("../docs/exercise-library.json", import.meta.url));

const GROUPS = ["push", "pull", "squat", "hinge", "core", "arms"];
const LOADS = ["dumbbell", "bodyweight", "band_assist", "hold"];
const KNEE = ["low", "moderate", "high"];

export function validateLibrary(lib) {
  const errors = [];
  if (!Array.isArray(lib.exercises)) return ["exercises is missing or not a list"];
  const ids = new Set();
  const rungs = new Set();
  const isRange = (r) =>
    Array.isArray(r) && r.length === 2 && r.every(Number.isInteger) && r[0] >= 1 && r[0] <= r[1];

  for (const [i, e] of lib.exercises.entries()) {
    const at = `exercise ${i + 1} (${e.id ?? "no id"})`;
    for (const key of ["id", "name", "ladder", "cue"]) {
      if (typeof e[key] !== "string" || e[key].trim() === "") errors.push(`${at}: ${key} must be text`);
    }
    if (ids.has(e.id)) errors.push(`${at}: duplicate id`);
    ids.add(e.id);
    if (!lib.ladders?.[e.ladder]) errors.push(`${at}: ladder "${e.ladder}" is not in ladders`);
    if (!Number.isInteger(e.rung) || e.rung < 1) errors.push(`${at}: rung must be a whole number from 1`);
    const rungKey = `${e.ladder}#${e.rung}`;
    if (rungs.has(rungKey)) errors.push(`${at}: another exercise already sits on ${e.ladder} rung ${e.rung}`);
    rungs.add(rungKey);
    if (!GROUPS.includes(e.group)) errors.push(`${at}: group "${e.group}" is not one of ${GROUPS.join(", ")}`);
    if (!LOADS.includes(e.load)) errors.push(`${at}: load "${e.load}" is not one of ${LOADS.join(", ")}`);
    if (![0, 1, 2].includes(e.dumbbells)) errors.push(`${at}: dumbbells must be 0, 1, or 2`);
    if (!KNEE.includes(e.knee)) errors.push(`${at}: knee "${e.knee}" is not one of ${KNEE.join(", ")}`);
    for (const key of ["equipment", "context"]) {
      if (!Array.isArray(e[key]) || !e[key].every((x) => typeof x === "string")) {
        errors.push(`${at}: ${key} must be a list of text`);
      }
    }
    if (typeof e.unilateral !== "boolean") errors.push(`${at}: unilateral must be true or false`);
    if (e.reps !== null && !isRange(e.reps)) errors.push(`${at}: reps must be null or [min, max]`);
    if (e.seconds !== null && !isRange(e.seconds)) errors.push(`${at}: seconds must be null or [min, max]`);
  }
  return errors;
}

const text = (s) => `'${String(s).replaceAll("'", "''")}'`;
const textArray = (a) => (a.length ? `array[${a.map(text).join(", ")}]::text[]` : `'{}'::text[]`);
const num = (n) => (n === null || n === undefined ? "null" : String(n));

export function buildSeedSql(lib) {
  const rows = lib.exercises.map((e) =>
    [
      text(e.id),
      text(e.name),
      text(e.ladder),
      num(e.rung),
      text(e.group),
      text(e.load),
      num(e.dumbbells),
      textArray(e.equipment),
      textArray(e.context),
      e.unilateral ? "true" : "false",
      num(e.reps?.[0]),
      num(e.reps?.[1]),
      num(e.seconds?.[0]),
      num(e.seconds?.[1]),
      text(e.knee),
      text(e.cue),
    ].join(", "),
  );

  const columns =
    "id, name, ladder, rung, grp, load, dumbbells, equipment, context, unilateral, rep_min, rep_max, sec_min, sec_max, knee, cue";
  const updates = columns
    .split(", ")
    .filter((c) => c !== "id")
    .map((c) => `${c} = excluded.${c}`)
    .join(",\n  ");

  return [
    `-- Generated by scripts/build-seed.mjs from docs/exercise-library.json (library version ${lib.version}).`,
    `-- ${lib.exercises.length} exercises. Do not edit by hand: change the JSON and regenerate.`,
    ``,
    `insert into public.exercises (${columns}) values`,
    rows.map((r) => `  (${r})`).join(",\n"),
    `on conflict (id) do update set`,
    `  ${updates};`,
    ``,
  ].join("\n");
}

// Run directly: validate, then print the SQL.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const lib = JSON.parse(readFileSync(libraryPath, "utf8"));
  const errors = validateLibrary(lib);
  if (errors.length) {
    console.error(`The exercise library has ${errors.length} problem(s):\n- ${errors.join("\n- ")}`);
    process.exit(1);
  }
  process.stdout.write(buildSeedSql(lib));
}
